### PR TITLE
Try to fix all errors and warnings for 0.57.x

### PR DESCRIPTION
**Pull request by rsolomon**
I *think* I've got a usable solution here. It passed all tests except 1, and I removed that test because I think it's invalid: you shouldn't be able to override a `providedProp`.

The only new constraint is that functional components must be typed, either as `React.ComponentType` or `React.StatelessFunctionalComponent` for components without `defaultProps`, and the internal `ComponentWithDefaultProps` for those that do.

cc @rosskevin @AriaMinaei

### CODE REVIEW

**Comment by rsolomon** [comment]
Note that the required casting of Functional Components with defaultProps is one of 2 options: Alternatively, the lib could enforce that consumers use only class-based components when working with defaultProps. See https://github.com/facebook/flow/issues/2699

**Comment by rosskevin** [comment]
Great work @rsolomon.  I pulled/tested it and it looks good.

Given the reference to functional components, I don't think the lib should enforce use of class components, but perhaps this should be added to the readme, in big, bold type and link to the flow issue.

LGTM

**Comment by AriaMinaei** [comment]
Nice! I'm gonna merge this and open a separate issue on how to deal with edge cases.

**Comment by rsolomon** [comment]
Would it be possible to get this released as 0.2.0 or 0.2.0-beta4?

**Comment by AriaMinaei** [comment]
Published as beta.4

**Pull request merged**
