### PR TITLE
Variety of HOC injection tests

### PR DESCRIPTION
**Pull request by rosskevin**
Thanks to @rsolomon and his help with diagnosing this in https://github.com/callemall/material-ui/issues/8716

I set out to prove the case we were having in material-ui, yet I have not replicated it.  Further, this PR should be failing because I have intentionally altered suppressions, but it still passes. This leads me to believe that the new tests have just exposed that it is not functioning correctly (either flow 0.57.3 or this lib).

### CODE REVIEW

**Comment by rosskevin** [comment]
I've got some more examples to add, I think the stateless functions will break it.

**Comment by rosskevin** [comment]
@rsolomon - You can see from this commit that HOC usage is not raising errors:

https://github.com/digiaonline/react-flow-types/pull/14/commits/4e8486fb865e29393bf1fd846a8755cdf9697db6

Perhaps the last change impacted this?  Basically, flow is ignoring all the injection tests - they are all valid at this point (which is an error).

**Comment by rosskevin** [comment]
@rsolomon @AriaMinaei - as-is, these tests should be failing because I omitted the suppressions from `.flowconfig`, but they are not failing as expected.  Further, flow is not failing with `unused suppression` errors, and it is not warning about them either.  For the injected test variations, anything works.

Thoughts?

**Comment by AriaMinaei** [comment]
Firstly, thanks for the PR! The tests are now much easier to maintain.

As to unused suppressions now showing up, try adding this to .flowconfig:
```ini
[options]
include_warnings=true

[lints]
all=error
```

**Comment by rosskevin** [comment]
Thanks @AriaMinaei - it looks like there are now several unused suppression warnings (it's too bad we cannot make these errors).

```
Warning: tests/index.js:55
 55:     // $FlowExpectError
         ^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

Warning: tests/index.js:92
 92:     // $FlowExpectError
         ^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

Warning: tests/index.js:94
 94:     // $FlowExpectError
         ^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

Warning: tests/index.js:96
 96:     // $FlowExpectError
         ^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

Warning: tests/index.js:125
125:       // $FlowExpectError
           ^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

Warning: tests/index.js:137
137:     // $FlowExpectErrorTestClassComponent
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

Warning: tests/index.js:143
143:     // $FlowExpectErrorTestClassComponent
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

Warning: tests/index.js:149
149:     // $FlowExpectErrorTestClassComponent
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

Warning: tests/index.js:155
155:     // $FlowExpectErrorTestClassComponent
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

Warning: tests/index.js:165
165:     // $FlowExpectErrorTestFunctionalComponent
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

Warning: tests/index.js:171
171:     // $FlowExpectErrorTestFunctionalComponent
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

Warning: tests/index.js:177
177:     // $FlowExpectErrorTestFunctionalComponent
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

Warning: tests/index.js:183
183:     // $FlowExpectErrorTestFunctionalComponent
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression


Found 13 warnings
```

Any help is appreciated here - it looks like it is fundamentally no longer working with flow 0.57.3.  I've already spent a ton of time getting to this point and have to move on to other tasks.

**Comment by rsolomon** [comment]
@rosskevin I'm going through these 1 by 1, so this is only for the error above on line 55.

This won't catch wrong types because the `$Diff` in `HigherOrderComponent` strips out the proptype from the generated component instead of making it optional.

Specifically, if we look at `provideString1`:

```
declare var provideString1: HigherOrderComponent<{}, {string1: string}>;
```

We're defining `RequiredProps` as `{}` and `ProvidedProps` as `{string1: string}`. I'll get back to this a bit lower down.

Now we create `ProvideString1OfValidFunctionalComponent`:

```
const ProvideString1OfValidFunctionalComponent = provideString1(ValidFunctionalComponent);
```

That means that, inside of `HigherOrderComponent`, we have:

1. `RequiredProps` as `{}`
2. `ProvidedProps` as `{string1: string}`
3. `DefaultProps` as `{number1: number}`
4. `OriginalProps` as `{string1: string, number1: number}`

Given the following `type equation`:

```
RequiredProps & $Diff<OriginalProps, ProvidedProps & DefaultProps>
```

We're left with

```
{} & $Diff<{string1: string, number1: number}, {string1: string} & {number1: number}>
```

The `$Diff` arguments cancel each-other out, so we're ultimately just passing `{} & {}` as the props.

**Comment by rsolomon** [comment]
I think `$Shape` is our savior, for that issue:

```
export type HigherOrderComponent<RequiredProps, ProvidedProps> =
  & (<OriginalProps, DefaultProps>(component: ComponentWithDefaultProps<DefaultProps, OriginalProps>) =>
      React.ComponentType<RequiredProps & $Shape<OriginalProps & DefaultProps> & $Diff<OriginalProps, ProvidedProps & DefaultProps>>)
  & (<OriginalProps>(component: React.ComponentType<OriginalProps>) => React.ComponentType<RequiredProps & $Diff<OriginalProps, ProvidedProps>>);
```

Still 8 errors, but better than 13 :)

**Comment by rsolomon** [comment]
The composition is proving tricky. 2 issues I'm noticing:

1. It seems to be both inferring component types from instantiations, rather than component definition
2. `$Diff` is spitting out a union of an exact and inexact type. I really don't know why, but once this gets nested it just goes wild.

I've got a bit of a sandbox setup here with the above issues, with some possibly helpful comments inline:

https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32sDcyVAHljyhcATwxVQAYWhlSU5lgB2VJbgA8ABSYZSAGlABlXMVxUAfKAC8iUNNmlS66nVwA6BZlgq1WnfqMTM3NzXkQBIXwxCXs5T2VVXAB1FFwACwARKkhiAFdoXG1YXXUsnPzC-wMi3QNjUwtrW1jHeO9Ev2KA+uDQADJQAG8AE2y8gprSAC5QMvHKroBfMIicKPFJNp9k1MyxisnS-Ymq0EnLGzsXeg9FdrUAFQ3O3UsBkeOF3Rm5g-9l5DhQRrEQbUAACRQAHM0lRsAB5bCjbBbDrUACOuRQHGGk2qTAAbihRrj-BdmgMABTqRHQlBKYjQPGzT7nSm0O7bGaotQpdK-E5dI7lQW1UC0qH0xnnACU1nMzTsV047h5uCeEmcVEx2KopK6-VAABJDGliJqMVicZNDRKpUyyYajRkUJBIDTsHSGQ6uvjYESSTaBgKvqQQjKKaBqXbvWyOV4uZQVbcE4kNVQPV7pWS5VZLNdVZy089Lbr9bonS63ZnJbHTkUA3rzuYZWFRrRZBxQATiNhQBhCcSqMZPUooQBGGaQmFwxHItXqQaLAyDUi4UcTmZrjeLUKIdudyQ9vsD-1DgByuTQACM4eOAIJKYaljiXm9wgBMU+hsIRSLhC6DEoV63tgX6gMB77YMuQyQaBk4QSBcK7rwB69kevagBwOqvkh2AAMzfjOf7zkWvhAXhhGIVBMFLnuSoMaAiAckoa6gAAaoyxIAGK5Eo9AoN4jJqjMBZuD0VDQFQji8fxuCCd6gHbvSm6gMpY4GHBd4zFp0EXFGp7fEM6mqSZml4QhumLLmljqMMKAEqAwD0UqiAgNI46gKowzkLkGCgGaRJjiIaQoOQ0RUDMblgAABmq6aLrpVFWYalIUVBll4eZUHJVlanripCEmYsoAAD5DKVumZVB2WgblNX5RuRUFWOpXWeYMXMd4bFSJ5VhYdqVpUG+dWUpx0A8XxAlCdAaqtoqjFdax+D8NYoDqL1jWFVYABEJk7dR8FWIM44lUlx34SVznIO5bh3aA8ChbQaSgGFoD2W6KC0BUoCQDgxpVpAIiwP2vakFQBikCDUgfl5T6+f5gUqVM0WgHFZHqs86WgeBKXvJVlE6XlJnNRubUdajACSKiCBNtDENe0CiL9OBQlQuDycF6SmIdn4kE+vMEV5-Bhe4S09bD-Wno2I13o+z6DbqstgZSvXzYxrksWxzP9RtsMk7t+2Cx+x2nYL+EXVde4LQxNuuRrdhuQQ4v4G04PDGqa3S0OI6FZS3ujMrD5Pi+w14R+lLYUNyv4WNXHDLJ02KRjMqp7wBDAEAA

I've got to step out for a while, might not get back to this until tomorrow. Hopefully this helps in the meantime.

**Comment by rosskevin** [comment]
@AriaMinaei I suggest we merge this PR with the test changes as-is to allow @rsolomon  and others to collaborate.  It doesn't change the source, just exposes the warnings and adds test cases.

**Comment by AriaMinaei** [comment]
Yes, good idea

**Comment by rsolomon** [comment]
I think this problem might either not be possible with the current implementation of Components / $Diff, or above my abilities :(

This is the best I was able to come up with:

```
export type HigherOrderComponent<RequiredProps, ProvidedProps> =
  & (<OriginalProps, DefaultProps>(component: ComponentWithDefaultProps<DefaultProps, OriginalProps>) =>
     React.ComponentType<RequiredProps & $Shape<RequiredProps & OriginalProps> & $Diff<OriginalProps, ProvidedProps & DefaultProps>>)
  & (<OriginalProps>(component: React.ComponentType<OriginalProps>) => React.ComponentType<RequiredProps & $Shape<OriginalProps & RequiredProps> & $Diff<OriginalProps & RequiredProps, ProvidedProps>>);
```

It unfortunately requires you to explicitly type functional components as `ComponentType<T>`, and still falls apart with composition.

**Comment by rsolomon** [comment]
Heads up: I'm going to try typing the MUI HoCs without `react-prop-types`.

**Pull request merged**
